[package]
name = "seiti_core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
good_lp = { version = "1.14.2", default-features = false, features = ["highs"] }
